name: Model Retraining on Push to Main
on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  retrain:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run tests first
      run: |
        python src/test.py
      continue-on-error: false  # Stop if tests fail
    
    - name: Generate and Store Timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
      id: timestamp 
    
    - name: Train Model
      run: |
        timestamp=$(cat timestamp.txt)
        python ./src/train_model.py --timestamp "$timestamp"
    
    - name: Evaluate Model and Log Metrics
      run: |
        timestamp=$(cat timestamp.txt)
        python ./src/evaluate_model.py --timestamp "$timestamp"
        metrics_filename="${timestamp}_metrics.json"
        mv $metrics_filename $GITHUB_WORKSPACE/metrics/$metrics_filename
      continue-on-error: false
    
    - name: Store and Version the New Model
      run: |
        timestamp=$(cat timestamp.txt)
        model_filename="wine_model_${timestamp}_rf_model.joblib"
        mv $model_filename $GITHUB_WORKSPACE/models/$model_filename
    
    - name: Commit and Push Changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action Bot"
        git add models/ metrics/ data/ mlruns/
        git commit -m "🤖 Add model v${timestamp} and metrics" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}